version: "3.7"

services:
    nginx:
        image: andreasbogh/nodenginx
        networks:
            - frontend
        depends_on:
            - web
        ports:
            - 80:80
    web:
        image: andreasbogh/nodeserver
        networks:
            - frontend
            - backend
        depends_on:
            - redis
        deploy:
            endpoint_mode: dnsrr
    redis:
        image: andreasbogh/noderedis
        networks:
            - backend

networks:
    frontend:
    backend: